service: audio-predictive-maintenance-demo
image: ctballentine/audio-predictive-maintenance-demo

servers:
  web:
    hosts:
      - 5.161.51.45
    env:
      clear:
        DB_HOST: draw-poker-db
        POSTGRES_USER: postgres
        POSTGRES_DB: audio_predictive_maintenance_production
      secret:
        - RAILS_MASTER_KEY
        - POSTGRES_PASSWORD

proxy:
  ssl: true
  host: telemetry.thesofttimes.com
  app_port: 3000

registry:
  server: ghcr.io
  username: ctballentine
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

asset_path: /rails/public/assets
